"""Unit tests for ClaudeMark file provenance and cleaners."""

from pathlib import Path
import pytest
from claudemark.provenance.c2pa import inspect_c2pa_bytes
from claudemark.provenance.documents import clean_document, inspect_document
from claudemark.provenance.exif_xmp import inspect_exif_xmp_bytes
from claudemark.provenance.images import clean_image_file, inspect_image_file


def test_c2pa_inspection_bytes():
    clean_bytes = b"Hello world clean image bytes"
    res_clean = inspect_c2pa_bytes(clean_bytes)
    assert not res_clean["has_c2pa"]

    c2pa_mock_bytes = b"\x00\x00\x00 c2pa.assertions urn:c2pa:test"
    res_mock = inspect_c2pa_bytes(c2pa_mock_bytes)
    assert res_mock["has_c2pa"]
    assert len(res_mock["indicators"]) >= 1


def test_exif_xmp_inspection_bytes():
    mock_ai_bytes = b"<x:xmpmeta>Generated by Midjourney v6</x:xmpmeta>"
    res = inspect_exif_xmp_bytes(mock_ai_bytes)
    assert res["has_xmp"]
    assert res["has_ai_metadata"]
    assert "midjourney" in res["ai_markers"]


def test_document_inspect_and_clean_txt(tmp_path):
    txt_file = tmp_path / "test.txt"
    txt_file.write_text("Hello\u200b world with zero width", encoding="utf-8")

    rep = inspect_document(txt_file)
    assert rep.file_format == "txt"
    assert rep.unicode_anomalies == 1
    assert rep.suspicious

    cleaned_file = tmp_path / "cleaned.txt"
    clean_res = clean_document(txt_file, cleaned_file)
    assert clean_res.success
    assert cleaned_file.read_text(encoding="utf-8") == "Hello world with zero width"


def test_document_inspect_and_clean_markdown(tmp_path):
    md_file = tmp_path / "test.md"
    md_file.write_text("---\ngenerator: chatgpt\n---\n# Title\n\nContent here.\n", encoding="utf-8")

    rep = inspect_document(md_file)
    assert rep.file_format == "md"

    cleaned_file = tmp_path / "cleaned.md"
    clean_res = clean_document(md_file, cleaned_file)
    assert clean_res.success
    assert "generator" not in cleaned_file.read_text(encoding="utf-8")
