"""Integration tests for multi-format file inspection, cleaning, and text forensics."""

from pathlib import Path
import pytest

from claudemark.core.unicode_forensics import analyze_unicode_forensics
from claudemark.detectors.registry import detector_registry
from claudemark.provenance.batch import clean_single_file, inspect_single_file


def test_html_document_inspection_and_cleaning(tmp_path):
    html_file = tmp_path / "sample_ai.html"
    html_file.write_text(
        '<!DOCTYPE html><html><head><meta name="generator" content="ChatGPT">'
        '<meta name="ai-model" content="Claude-3.5-Sonnet"></head>'
        '<body><p>Hello\u200B world with AI provenance markers.</p></body></html>',
        encoding="utf-8",
    )

    rep = inspect_single_file(html_file)
    assert rep.file_format in ("html", "htm")
    assert rep.suspicious
    assert rep.has_ai_metadata

    cleaned_out = tmp_path / "cleaned.html"
    clean_rep = clean_single_file(html_file, cleaned_out)
    assert clean_rep.success
    assert cleaned_out.is_file()
    clean_text = cleaned_out.read_text(encoding="utf-8")
    assert "generator" not in clean_text
    assert "\u200b" not in clean_text


def test_markdown_document_inspection_and_cleaning(tmp_path):
    md_file = tmp_path / "sample_ai.md"
    md_file.write_text(
        "---\ntitle: AI Generated Report\nauthor: Claude\n---\n\n"
        "# Executive Summary\n\nThis manuscript contains\u200C invisible steganographic marks.\n",
        encoding="utf-8",
    )

    rep = inspect_single_file(md_file)
    assert rep.file_format == "md"
    assert rep.suspicious

    cleaned_out = tmp_path / "cleaned.md"
    clean_rep = clean_single_file(md_file, cleaned_out)
    assert clean_rep.success
    assert cleaned_out.is_file()
    clean_text = cleaned_out.read_text(encoding="utf-8")
    assert "author: Claude" not in clean_text
    assert "\u200c" not in clean_text


def test_svg_vector_inspection_and_cleaning(tmp_path):
    svg_file = tmp_path / "sample_meta.svg"
    svg_file.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">'
        '<metadata><ai:provenance xmlns:ai="http://example.com/ai">Midjourney v6</ai:provenance></metadata>'
        '<!-- Generated by AI Model --><circle cx="50" cy="50" r="40" fill="red"/>'
        '</svg>',
        encoding="utf-8",
    )

    rep = inspect_single_file(svg_file)
    assert rep.file_format == "svg"
    assert rep.suspicious

    cleaned_out = tmp_path / "cleaned.svg"
    clean_rep = clean_single_file(svg_file, cleaned_out)
    assert clean_rep.success
    assert cleaned_out.is_file()
    clean_svg = cleaned_out.read_text(encoding="utf-8")
    assert "<metadata>" not in clean_svg
    assert "Generated by AI" not in clean_svg


def test_watermarked_text_forensics(tmp_path):
    txt_file = tmp_path / "watermarked.txt"
    txt_file.write_text(
        "Confidential\u200b manuscript\u200c payload\ufeff test\u00a0here.",
        encoding="utf-8",
    )

    rep = analyze_unicode_forensics(txt_file.read_text(encoding="utf-8"))
    assert rep.total_anomalies >= 4
    assert rep.has_anomalies
    assert rep.zero_width_count >= 3
    assert rep.nbsp_count == 1


def test_stylometry_detectors_discrimination():
    ai_sample = (
        "In conclusion, it is important to analyze comprehensive paradigms across various stakeholders. "
        "Furthermore, modern frameworks ensure seamless integration and optimal efficiency across all organizational workflows. "
        "Therefore, strategic alignment remains vital for long-term sustainability."
    )
    hum_sample = (
        "We took the backroads through the hills yesterday. It rained most of the morning, "
        "so the trails were soaked and slick with mud. By afternoon though, the sun came out "
        "and we stopped at an old wooden bridge to rest."
    )

    det = detector_registry.get("claude")
    res_ai = det.detect(ai_sample)
    res_hum = det.detect(hum_sample)

    assert 0.0 <= res_ai.signal_score <= 1.0
    assert 0.0 <= res_hum.signal_score <= 1.0
